app:
  environment: "development"
  debug: true
  hide_banner: false
  hide_port: false
  api:
    http:
      host: "127.0.0.1"
      port: "8088"
  logger:
    lvl: "debug"
    encoding: "console"
    outputPaths: [ "stdout" ]
    errorOutputPaths: [ "stderr" ]
    encoderConfig:
      messageKey: "message"
      levelKey: "level"
      timeKey: "time"
      nameKey: "logger"
      callerKey: "caller"
      stacktraceKey: "stacktrace"
      lineEnding: "\n"
      levelEncoder: "lowercase"
      timeEncoder: "iso8601"
    development: true
    caller: true
    stacktrace: "warn"
  pgsql:
    pgpool:
      default:
        nodes: [
          "postgres://user:password@127.0.0.1:5432/db?sslmode=disable&client_encoding=UTF8"
        ]
        max_conns: 5
        min_conns: 1
        max_conn_lifetime: "90m"
        max_conn_idle_time: "31m"
        health_check_period: "1m"
        # lazy_conn: false
        # prefer_simple_protocol: true
    migrations:
      table: "migrations"
      scheme: "public"
      host: "127.0.0.1"
      port: "5432"
      user: "user"
      password: "password"
      dbname: "db"
      conn_max_lifetime: '10m'
      options:
        sslmode: "disable"
        encoding: "UTF8"